[workspace]
members = [
    'core/id',
    'systems/crypto',
    'core/wasm_management',
    #'wasm_apps/attestation',
    #'wasm_apps/systems/crypto'
]

exclude = [
    'core/build',
    'wasm_apps/panic',
    'wasm_apps/attestation',
    'wasm_apps/crypto',
]