[package]
name = "propagative_attestation"
version = "0.1.0"
authors = ["Sora Suegami <suegamisora@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
